### ISSUE TITLE
Error in smpmap.py

### ISSUE THREAD

**Issue by DefinitlyEvil** [SpockBotMC/SpockBot#207] opened 2016-01-04 16:23 UTC
```
Traceback (most recent call last):
  File "example.py", line 87, in <module>
    client.start(SERVER, 25565)
  File "D:\Programs\Python35\lib\site-packages\spockbot-0.1.3-py3.5.egg\spockbot\plugins\helpers\start.py", line 34, in start
  File "D:\Programs\Python35\lib\site-packages\spockbot-0.1.3-py3.5.egg\spockbot\plugins\core\event.py", line 25, in event_loop
  File "D:\Programs\Python35\lib\site-packages\spockbot-0.1.3-py3.5.egg\spockbot\plugins\core\event.py", line 34, in run_continuous
  File "D:\Programs\Python35\lib\site-packages\spockbot-0.1.3-py3.5.egg\spockbot\plugins\core\event.py", line 62, in emit
  File "D:\Programs\Python35\lib\site-packages\spockbot-0.1.3-py3.5.egg\spockbot\plugins\core\timers.py", line 132, in tick
  File "D:\Programs\Python35\lib\site-packages\spockbot-0.1.3-py3.5.egg\spockbot\plugins\core\timers.py", line 28, in update
  File "D:\Programs\Python35\lib\site-packages\spockbot-0.1.3-py3.5.egg\spockbot\plugins\core\timers.py", line 31, in fire
  File "D:\Github\example_plugin.py", line 109, in periodic_event_handler
    block_pos.z)
  File "D:\Programs\Python35\lib\site-packages\spockbot-0.1.3-py3.5.egg\spockbot\plugins\tools\smpmap.py", line 160, in get_block
TypeError: list indices must be integers or slices, not float
```

**Comment by Gjum** [comment] 2016-01-04 16:27
@nickelpro sounds like it wasn't such a good idea to remove that line bf7002f89e349abcb70db871cc9deba51e054b37

**Comment by DefinitlyEvil** [comment] 2016-01-04 16:33
@Gjum Thx for rapid respond, so it can be fixed now?

**Comment by DefinitlyEvil** [comment] 2016-01-04 16:34
Btw it also says `list indicies must be integer` at line 50: 
```
        return self.data[x + ((y * 16) + z) * 16]
```

**Comment by rom1504** [comment] 2016-01-04 16:36
@DefinitlyEvil if you want it to work right now, convert the position to int yourself before calling the get_block function

**Comment by DefinitlyEvil** [comment] 2016-01-04 16:37
@rom1504 I was playing around with example.py. xD And TONs of errors messed me up.

**Comment by Gjum** [comment] 2016-01-04 16:38
I'm not sure if we will "fix" that, because you are supposed to only supply integer (block) coordinates.

So instead of `get_block(floaty_pos)`, it should be `get_block(floaty_pos.floor())`.

The examples are quite outdated, see also #188.

**Comment by DefinitlyEvil** [comment] 2016-01-04 16:40
@Gjum Okay. ;P Thanks for making this awesome project and thanks for noticing me about that example script. xD

**Comment by DefinitlyEvil** [comment] 2016-01-04 16:42
@Gjum Btw I didn't call `get_block()` in example.py, it seems that some other script invoked it. xD

**Comment by nickelpro** [comment] 2016-01-04 16:46
I dislike having to do that conversion there. Rightfully if we do it there we should do it for all the `get` and `set` functions in smpmap.

Really I'd like to just track down everywhere we're passing floats to smpmap, fix them, and then just ban passing floats when you really should pass an integer

**Comment by Gjum** [comment] 2016-01-04 16:50
I agree. Although the error message can be a bit misleading.

**Comment by nickelpro** [comment] 2016-01-04 16:52
So we're agreed this is not an error in smpmap then. This is a problem with our horribly outdated examples. I'll put it on my "high priority" ToDo list along with vehicle Physics and auth tokens

**Comment by DefinitlyEvil** [comment] 2016-01-04 16:59
@nickelpro Thx so much. Muah!

**Comment by Gjum** [comment] 2016-03-13 04:22
fixed in c09dbfaf85f936dce8ce99e6f99be057e51167b0

**Closed by Gjum** 2016-03-13 04:22 UTC
Labels: bug

**Comment by suBDavis** [comment] 2016-03-29 17:45
This appears to still be an issue...

In offline mode, the bot crashes after joining the game on
`TypeError: list indices must be integers, not float`

Full stack trace:
```
[INFO]: My position: PlayerPosition(0, 0, 0) pitch: 0.0 yaw: 0.0
[DEBUG]: EVENTCORE: Exception while emitting physics_tick None
[DEBUG]: EVENTCORE: Exception while emitting event_tick None
Traceback (most recent call last):
  File "example.py", line 56, in <module>
    client.start(SERVER, 25565)
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/helpers/start.py", line 34, in start
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/core/event.py", line 29, in event_loop
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/core/event.py", line 36, in run_continuous
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/core/event.py", line 62, in emit
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/core/timers.py", line 132, in tick
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/core/timers.py", line 28, in update
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/core/timers.py", line 31, in fire
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/core/ticker.py", line 19, in client_tick
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/core/event.py", line 62, in emit
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/helpers/physics.py", line 109, in physics_tick
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/helpers/physics.py", line 152, in get_mtv
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/tools/collision.py", line 43, in check_collision
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/tools/collision.py", line 51, in block_collision
  File "build/bdist.linux-x86_64/egg/spockbot/plugins/tools/smpmap.py", line 230, in get_block
TypeError: list indices must be integers, not float
```
I checked, and my code does have the fix applied in commit c09dbfa.

**Comment by rom1504** [comment] 2016-03-29 17:52
@suBDavis you are flooring the position before passing it to get_block, right ?

**Comment by suBDavis** [comment] 2016-03-29 18:23
@rom1504 I'm using the example plugin, which is indeed performing the floor on line 100
`        block_pos = self.clientinfo.position.floor()`

**Comment by nickelpro** [comment] 2016-03-29 19:13
Apparently Physics is generating a floating point block positions which I don't understand

**Comment by suBDavis** [comment] 2016-03-29 20:19
Are you able to reproduce?  

I was trying to document my entire configuration (python version, steps to install, etc) and I started over.  I'm now unable to reproduce that error.

**Comment by nickelpro** [comment] 2016-03-29 20:58
I just said that based on the stack trace. That sort of thing should be impossible with the current code base. Old version?

**Comment by suBDavis** [comment] 2016-03-29 21:40
Definitely not.  both came from a git clone https://github.com/SpockBotMC/SpockBot

However, I _could_ have had some outdated packages... or... something.  I originally installed SpockBot at the system level, and then tried to repro it in a virtual environment, which would have installed the dependencies fresh from pip.

**Comment by nickelpro** [comment] 2016-03-29 22:20
Dependencies don't enter into it. The offending `get_block` call is here:
https://github.com/SpockBotMC/SpockBot/blob/master/spockbot/plugins/tools/collision.py#L51

Which takes a block position from a generator that clearly floors its base position:
https://github.com/SpockBotMC/SpockBot/blob/master/spockbot/plugins/tools/collision.py#L15-L20

If this can't be reproduced I'm not sure how to fix
